Lesson 3
h00gin/geekshop pull request #3
Opened 2021-06-04 07:34 UTC by h00gin

2021-06-04 09:19 UTC, vprinz requested changes

2021-06-04 09:19 UTC, Vokler commented on geekshop/urls.py
> +    path('/products', include('products.urls', namespace='products')),
А почему слэш в начале?) Он должен быть в конце.
Иначе у вас потом (на 8 уроке) адрес конкретного товара будет выглядеть `.../products2/`, а должен  `.../products/2/`

2021-06-04 09:19 UTC, Vokler commented
По поводу кодировки - посмотрите, возможно, это решение поможет
https://stackoverflow.com/questions/12632862/using-utf-8-encoded-json-fixture-file-in-django

2021-06-04 09:25 UTC, h00gin commented on geekshop/urls.py
> +    path('/products', include('products.urls', namespace='products')),
зашпарился) исправил

2021-06-04 18:28 UTC, Vokler commented on geekshop/urls.py
> +    path('/products', include('products.urls', namespace='products')),
А вы точно запушили изменения? Не вижу, чтобы что-то изменилось в репозитории

2021-06-04 18:33 UTC, h00gin commented on geekshop/urls.py
> +    path('/products', include('products.urls', namespace='products')),
теперь да)

2021-06-07 07:31 UTC, Vokler approved these changes

2021-06-07 07:31 UTC, merged